services:
  - type: web
    name: tgbot-zcdz
    runtime: python
    plan: starter
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m bot.main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: WEBAPP_URL
        value: https://tgbot-zcdz.onrender.com
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SUPPORT_USERNAME
        sync: false
      - key: MONGO_URI
        sync: false
      - key: API_ADMIN_TOKEN
        sync: false
      - key: LUA_API_CRYPTO_MODE
        value: "3"
      - key: LUA_API_KEY_ID
        sync: false
      - key: LUA_API_RSA_PRIVATE_JWK_B64
        sync: false
      - key: TABLE_CSV_URL
        sync: false
      - key: ANALOGUES_CSV_URL
        sync: false
      - key: CARS_CSV_URL
        sync: false
      - key: TRIBUTE_API_KEY
        sync: false
      - key: TRIBUTE_SUBSCRIPTION_URL
        value: https://t.me/tribute/app?startapp=sYQs
      - key: TRIBUTE_DEBUG_WEBHOOKS
        value: "0"
      - key: TRIBUTE_ALLOWED_CHANNEL_IDS
        value: "479458"
      - key: TRIBUTE_ALLOWED_CHANNEL_NAMES
        value: ""
      - key: TRIBUTE_ALLOWED_SUBSCRIPTION_IDS
        value: "233892"
      - key: TRIBUTE_PERIOD_ID_1M
        value: "429551"
      - key: TRIBUTE_PERIOD_ID_3M
        sync: false
      - key: TRIBUTE_PERIOD_ID_6M
        sync: false
      - key: TRIBUTE_PERIOD_ID_FOREVER
        sync: false
      - key: TG_CHANNEL_URL
        sync: false
      - key: FUNPAY_URL_1M
        value: https://funpay.com/lots/offer?id=45877171
      - key: FUNPAY_URL_3M
        value: https://funpay.com/lots/offer?id=45877215
      - key: FUNPAY_URL_6M
        value: https://funpay.com/lots/offer?id=45877232
      - key: FUNPAY_URL_FOREVER
        value: https://funpay.com/lots/offer?id=45877250
      - key: REQUISITES_CARD
        value: 9112 3801 7082 5501
      - key: ZIP_FILE_PATH
        value: ./Price_by_KALYVAN.zip
      - key: ADMIN_WEB_SECRET_PATH
        sync: false
